[build]
  command = "npm run build"
  publish = "build/client"
  functions = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix-server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31560000, immutable"

[build.environment]
  NODE_VERSION = "20.5.0"