[build]
command = "npm run build"
publish = "build/client"

[functions]
included_files = ["locales/**, img/**"]
timeout = 20

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

[build.environment]
NODE_VERSION = "20.5.0"

[build.processing]
skip_processing = false

[build.processing.css]
minify = true
bundle = true
[build.processing.js]
minify = true
bundle = true
[build.processing.html]
pretty_urls = true
[build.processing.images]
compress = true

# Enable Brotli compression
[build.processing.brotli]
enabled = true
quality = 11