[build]
command = "npm run build"
publish = "build/client"

[functions]
  included_files = ["locales/**, img/**"]

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

[build.environment]
  NODE_VERSION = "20.5.0"

[build.processing.css]
minify = true
[build.processing.js]
minify = true
[build.processing.images]
compress = true