const data = {
  article: {
    id: "article.id",
    heading: "article.heading",
    url: "article.url",
    category: "article.category",
    editor: "article.editor",
    date: "article.date",
    readTime: "article.readTime",
    resume: "article.resume",
    prosTitle: "article.prosTitle",
    consTitle: "article.consTitle",
    content: [
      {
        id: "article.content.0.id",
        title: "article.content.0.title",
        paragraphs: [
          "article.content.0.paragraphs.0",
          "article.content.0.paragraphs.1",
          "article.content.0.paragraphs.2",
        ],
      },
      {
        id: "article.content.1.id",
        title: "article.content.1.title",
        img: "article.content.1.img",
        altText: "article.content.1.altText",
        pros: ["article.content.1.pros.0", "article.content.1.pros.1"],
        cons: ["article.content.1.cons.0", "article.content.1.cons.1"],
        paragraphs: [
          "article.content.1.paragraphs.0",
          "article.content.1.paragraphs.1",
          "article.content.1.paragraphs.2",
          "article.content.1.paragraphs.3",
        ],
      },
      {
        id: "article.content.2.id",
        title: "article.content.2.title",
        img: "article.content.2.img",
        altText: "article.content.2.altText",
        pros: ["article.content.2.pros.0", "article.content.2.pros.1"],
        cons: ["article.content.2.cons.0"],
        paragraphs: [
          "article.content.2.paragraphs.0",
          "article.content.2.paragraphs.1",
          "article.content.2.paragraphs.2",
          "article.content.2.paragraphs.3",
          "article.content.2.paragraphs.4",
        ],
      },
      {
        id: "article.content.3.id",
        title: "article.content.3.title",
        img: "article.content.3.img",
        altText: "article.content.3.altText",
        pros: [
          "article.content.3.pros.0",
          "article.content.3.pros.1",
          "article.content.3.pros.2",
        ],
        cons: ["article.content.3.cons.0"],
        paragraphs: [
          "article.content.3.paragraphs.0",
          "article.content.3.paragraphs.1",
          "article.content.3.paragraphs.2",
          "article.content.3.paragraphs.3",
          "article.content.3.paragraphs.4",
        ],
      },
      {
        id: "article.content.4.id",
        title: "article.content.4.title",
        img: "article.content.4.img",
        altText: "article.content.4.altText",
        pros: [
          "article.content.4.pros.0",
          "article.content.4.pros.1",
          "article.content.4.pros.2",
        ],
        cons: ["article.content.4.cons.0", "article.content.4.cons.1"],
        paragraphs: [
          "article.content.4.paragraphs.0",
          "article.content.4.paragraphs.1",
          "article.content.4.paragraphs.2",
          "article.content.4.paragraphs.3",
          "article.content.4.paragraphs.4",
          "article.content.4.paragraphs.5",
        ],
      },
      {
        id: "article.content.5.id",
        title: "article.content.5.title",
        img: "article.content.5.img",
        altText: "article.content.5.altText",
        pros: ["article.content.5.pros.0", "article.content.5.pros.1"],
        cons: ["article.content.5.cons.0", "article.content.5.cons.1"],
        paragraphs: [
          "article.content.5.paragraphs.0",
          "article.content.5.paragraphs.1",
          "article.content.5.paragraphs.2",
          "article.content.5.paragraphs.3",
          "article.content.5.paragraphs.4",
          "article.content.5.paragraphs.5",
        ],
      },
      {
        id: "article.content.6.id",
        title: "article.content.6.title",
        img: "article.content.6.img",
        altText: "article.content.6.altText",
        pros: [
          "article.content.6.pros.0",
          "article.content.6.pros.1",
          "article.content.6.pros.2",
          "article.content.6.pros.3",
        ],
        cons: ["article.content.6.cons.0", "article.content.6.cons.1"],
        paragraphs: [
          "article.content.6.paragraphs.0",
          "article.content.6.paragraphs.1",
          "article.content.6.paragraphs.2",
          "article.content.6.paragraphs.3",
          "article.content.6.paragraphs.4",
          "article.content.6.paragraphs.5",
        ],
      },
      {
        id: "article.content.7.id",
        title: "article.content.7.title",
        img: "article.content.7.img",
        altText: "article.content.7.altText",
        pros: [
          "article.content.7.pros.0",
          "article.content.7.pros.1",
          "article.content.7.pros.2",
        ],
        cons: ["article.content.7.cons.0", "article.content.7.cons.1"],
        paragraphs: [
          "article.content.7.paragraphs.0",
          "article.content.7.paragraphs.1",
          "article.content.7.paragraphs.2",
          "article.content.7.paragraphs.3",
          "article.content.7.paragraphs.4",
          "article.content.7.paragraphs.5",
        ],
      },
      {
        id: "article.content.8.id",
        title: "article.content.8.title",
        img: "article.content.8.img",
        altText: "article.content.8.altText",
        pros: [
          "article.content.8.pros.0",
          "article.content.8.pros.1",
          "article.content.8.pros.2",
        ],
        cons: ["article.content.8.cons.0", "article.content.8.cons.1"],
        paragraphs: [
          "article.content.8.paragraphs.0",
          "article.content.8.paragraphs.1",
          "article.content.8.paragraphs.2",
          "article.content.8.paragraphs.3",
          "article.content.8.paragraphs.4",
          "article.content.8.paragraphs.5",
        ],
      },
      {
        id: "article.content.9.id",
        title: "article.content.9.title",
        img: "article.content.9.img",
        altText: "article.content.9.altText",
        pros: [
          "article.content.9.pros.0",
          "article.content.9.pros.1",
          "article.content.9.pros.2",
        ],
        cons: ["article.content.9.cons.0", "article.content.9.cons.1"],
        paragraphs: [
          "article.content.9.paragraphs.0",
          "article.content.9.paragraphs.1",
          "article.content.9.paragraphs.2",
          "article.content.9.paragraphs.3",
          "article.content.9.paragraphs.4",
          "article.content.9.paragraphs.5",
          "article.content.9.paragraphs.6",
        ],
      },
      {
        id: "article.content.10.id",
        title: "article.content.10.title",
        img: "article.content.10.img",
        altText: "article.content.10.altText",
        pros: [
          "article.content.10.pros.0",
          "article.content.10.pros.1",
          "article.content.10.pros.2",
        ],
        cons: ["article.content.10.cons.0", "article.content.10.cons.1"],
        paragraphs: [
          "article.content.10.paragraphs.0",
          "article.content.10.paragraphs.1",
          "article.content.10.paragraphs.2",
          "article.content.10.paragraphs.3",
          "article.content.10.paragraphs.4",
          "article.content.10.paragraphs.5",
          "article.content.10.paragraphs.6",
        ],
      },
      {
        id: "article.content.11.id",
        title: "article.content.11.title",
        paragraphs: [
          "article.content.11.paragraphs.0",
          "article.content.11.paragraphs.1",
          "article.content.11.paragraphs.2",
          "article.content.11.paragraphs.3",
          "article.content.11.paragraphs.4",
        ],
      },
      {
        id: "article.content.12.id",
        title: "article.content.12.title",
        paragraphs: [
          "article.content.12.paragraphs.0",
          "article.content.12.paragraphs.1",
          "article.content.12.paragraphs.2",
          "article.content.12.paragraphs.3",
          "article.content.12.paragraphs.4",
          "article.content.12.paragraphs.5",
          "article.content.12.paragraphs.6",
        ],
        quote: "article.content.12.quote",
      },
    ],
    image: {
      url: "article.image.url",
      category: "article.image.category",
      alt: "article.image.alt",
    },
  },
};

export { data };
