import { CARMAKE_DATA, CARMODEL_DATA } from "./brandsData";

const filters = [
  {
    id: "make",
    size: { xs: 12, lg: 4 },
    type: "autosuggest",
    options: CARMAKE_DATA,
    isLabelVisible: false,
    showSuggestionsOnFocus: true,
    placeholder: "Marca",
    rightIcon: "FaChevronDown",
    label: "Marca",
  },
  {
    id: "model",
    size: { xs: 12, lg: 4 },
    type: "autosuggest",
    options: CARMODEL_DATA,
    conditionalDisabled: "make",
    isLabelVisible: false,
    showSuggestionsOnFocus: true,
    placeholder: "Modelo",
    rightIcon: "FaChevronDown",
    label: "Modelo",
  },
  {
    id: "location",
    size: { xs: 12, lg: 4 },
    type: "searchLocation",
    options: [
      { id: "rent", label: "getInTouch_form.radio.option1.label" },
      { id: "buy", label: "getInTouch_form.radio.option2.label" },
    ],
    isLabelVisible: false,
    leftIcon: "FaSearch",
    showSuggestionsOnFocus: true,
    clearButton: true,
    placeholder: "getInTouch_form.locationInput.placeholder",
    label: "getInTouch_form.locationInput.label",
  },
  {
    id: "price_from",
    label: "getInTouch_form.nameInput",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.priceFromInput.placeholder",
    type: "autosuggest",
    clearButton: true,
    showSuggestionsOnFocus: true,
    options: [
      { id: "0", label: "0" },
      { id: "1000", label: "1.000,00 $" },
      { id: "2000", label: "2.000,00 $" },
      { id: "5000", label: "5.000,00 $" },
      { id: "8000", label: "8.000,00 $" },
      { id: "10000", label: "10.000,00 $" },
      { id: "12000", label: "12.000,00 $" },
      { id: "14000", label: "14.000,00 $" },
      { id: "16000", label: "16.000,00 $" },
      { id: "18000", label: "18.000,00 $" },
      { id: "22000", label: "22.000,00 $" },
      { id: "26000", label: "26.000,00 $" },
      { id: "30000", label: "30.000,00 $" },
      { id: "40000", label: "40.000,00 $" },
      { id: "50000", label: "50.000,00 $" },
    ],
  },
  {
    id: "price_to",
    label: "getInTouch_form.nameInput",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.priceToInput.placeholder",
    showSuggestionsOnFocus: true,
    clearButton: true,
    type: "autosuggest",
    options: [
      { id: "0", label: "0" },
      { id: "1000", label: "1.000,00 $" },
      { id: "2000", label: "2.000,00 $" },
      { id: "5000", label: "5.000,00 $" },
      { id: "8000", label: "8.000,00 $" },
      { id: "10000", label: "10.000,00 $" },
      { id: "12000", label: "12.000,00 $" },
      { id: "14000", label: "14.000,00 $" },
      { id: "16000", label: "16.000,00 $" },
      { id: "18000", label: "18.000,00 $" },
      { id: "22000", label: "22.000,00 $" },
      { id: "26000", label: "26.000,00 $" },
      { id: "30000", label: "30.000,00 $" },
      { id: "40000", label: "40.000,00 $" },
      { id: "50000", label: "50.000,00 $" },
    ],
  },
  {
    id: "km_from",
    label: "getInTouch_form.nameInput",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.areaFromInput.placeholder",
    showSuggestionsOnFocus: true,
    clearButton: true,
    type: "autosuggest",
    options: [
      { id: "0", label: "0" },
      { id: "1000", label: "1000" },
      { id: "10000", label: "10000" },
      { id: "40000", label: "40000" },
      { id: "60000", label: "60000" },
      { id: "80000", label: "80000" },
      { id: "100000", label: "100000" },
      { id: "120000", label: "120000" },
      { id: "140000", label: "140000" },
      { id: "160000", label: "160000" },
      { id: "180000", label: "180000" },
      { id: "200000", label: "200000" },
      { id: "250000", label: "250000" },
    ],
  },
  {
    id: "km_to",
    label: "getInTouch_form.nameInput",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.areaToInput.label",
    showSuggestionsOnFocus: true,
    clearButton: true,
    type: "autosuggest",
    options: [
      { id: "0", label: "0" },
      { id: "1000", label: "1000" },
      { id: "10000", label: "10000" },
      { id: "40000", label: "40000" },
      { id: "60000", label: "60000" },
      { id: "80000", label: "80000" },
      { id: "100000", label: "100000" },
      { id: "120000", label: "120000" },
      { id: "140000", label: "140000" },
      { id: "160000", label: "160000" },
      { id: "180000", label: "180000" },
      { id: "200000", label: "200000" },
      { id: "250000", label: "250000" },
    ],
  },
  {
    id: "year_from",
    label: "Año desde",
    type: "number",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "Año desde:",
  },
  
  {
    id: "year_to",
    label: "Año hasta:",
    type: "number",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "Año hasta",
  },
  {
    id: "equipment",
    label: "getInTouch_form.equipment.placeholder",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.equipment.label",
    showSuggestionsOnFocus: true,
    type: "multiselect",
    options: [
      { id: "bluetooth", label: "Bluetooth" },
      { id: "backup_camera", label: "Backup Camera" },
      { id: "cruise_control", label: "Cruise Control" },
      { id: "navigation_system", label: "Navigation System" },
      { id: "sunroof", label: "Sunroof" },
      { id: "leather_seats", label: "Leather Seats" },
      { id: "remote_start", label: "Remote Start" },
      { id: "heated_seats", label: "Heated Seats" },
      { id: "blind_spot_monitoring", label: "Blind Spot Monitoring" },
      { id: "apple_carplay", label: "Apple CarPlay" },
      { id: "android_auto", label: "Android Auto" },
      { id: "keyless_entry", label: "Keyless Entry" },
      { id: "all_wheel_drive", label: "All-Wheel Drive" },
      { id: "parking_sensors", label: "Parking Sensors" },
      { id: "lane_departure_warning", label: "Lane Departure Warning" },
    ],
  },
  {
    id: "description",
    label: "getInTouch_form.inputDescription.label",
    type: "text",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.inputDescription.placeholder",
  },
  {
    id: "color",
    label: "Color",
    size: { xs: 12, lg: 4 },
    isLabelVisible: false,
    placeholder: "Color",
    showSuggestionsOnFocus: true,
    type: "multiselect",
    options: [
      { id: "red", label: "Red" },
      { id: "blue", label: "Blue" },
      { id: "black", label: "Black" },
      { id: "white", label: "White" },
      { id: "silver", label: "Silver" },
      { id: "gray", label: "Gray" },
      { id: "green", label: "Green" },
      { id: "yellow", label: "Yellow" },
    ],
  },
  {
    id: "fuelType",
    label: "Combustible",
    size: { xs: 12, lg: 4 },
    isLabelVisible: false,
    placeholder: "Combustible",
    showSuggestionsOnFocus: true,
    type: "multiselect",
    options: [
      { "id": "gasoline", "label": "Gasoline" },
      { "id": "diesel", "label": "Diesel" },
      { "id": "hybrid", "label": "Hybrid" },
      { "id": "electric", "label": "Electric" }
    ],
  },
  {
    id: "transmissionType",
    label: "Transmision",
    size: { xs: 12, lg: 4 },
    isLabelVisible: false,
    placeholder: "Transmision",
    showSuggestionsOnFocus: true,
    type: "multiselect",
    options: [
      { "id": "manual", "label": "Manual" },
      { "id": "automatic", "label": "Automatic" },
      { "id": "cvt", "label": "CVT" }
    ],
  },
  {
    id: "displacement",
    label: "Cilindrada",
    type: "text",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "Cilindrada",
  },
  {
    id: "power",
    label: "Potencia",
    type: "text",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "Potencia",
  },
  {
    id: "doors",
    type: "radio",
    size: { xs: 12, lg: 6 },
    options: [
      { id: "1", label: "1" },
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
      { id: "5", label: "5" },
      { id: "6", label: "6+" },
    ],
    defaultSelectedOption: "0",
    label: "getInTouch_form.rooms",
  },
  {
    id: "bathrooms",
    type: "radio",
    size: { xs: 12, lg: 6 },
    options: [
      { id: "1", label: "1" },
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
      { id: "5", label: "5" },
      { id: "6", label: "6+" },
    ],
    defaultSelectedOption: "0",
    label: "getInTouch_form.bathrooms",
  },
];

export const FILTERS = {
  type: "post",
  inputs: filters,
  hasSubmit: false,
  buttonLabel: "Search",
};
