import { CARMAKE_DATA, CARMODEL_DATA } from "./brandsData";

const inputs = [
  {
    id: "make",
    size: { xs: 12, lg: 4},
    type: "autosuggest",
    options: CARMAKE_DATA,
    isLabelVisible: false,
    showSuggestionsOnFocus: true,
    placeholder: "Marca",
    rightIcon: 'FaChevronDown',
    label: "Marca",
  },
  {
    id: "model",
    size: { xs: 12, lg: 4},
    type: "autosuggest",
    options: CARMODEL_DATA,
    conditionalDisabled: 'make',
    isLabelVisible: false,
    showSuggestionsOnFocus: true,
    placeholder: "Modelo",
    rightIcon: 'FaChevronDown',
    label: "Modelo",
  },
  {
    id: "location",
    size: { xs: 12, lg: 4 },
    type: "searchLocation",
    options: [
      { id: "rent", label: "getInTouch_form.radio.option1.label" },
      { id: "buy", label: "getInTouch_form.radio.option2.label" },
    ],
    isLabelVisible: false,
    leftIcon: 'FaSearch',
    showSuggestionsOnFocus: true,
    clearButton: true,
    placeholder: "getInTouch_form.locationInput.placeholder",
    label: "getInTouch_form.locationInput.label",
  },
  {
    id: "price_from",
    label: "getInTouch_form.nameInput",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.priceFromInput.placeholder",
    type: "autosuggest",
    clearButton: true,
    showSuggestionsOnFocus: true,
    options: [      
      { id: "0", label: "0" },
      { id: "1000", label: "1.000,00 $" },
      { id: "2000", label: "2.000,00 $" },
      { id: "5000", label: "5.000,00 $" },
      { id: "8000", label: "8.000,00 $" },
      { id: "10000", label: "10.000,00 $" },
      { id: "12000", label: "12.000,00 $" },
      { id: "14000", label: "14.000,00 $" },
      { id: "16000", label: "16.000,00 $" },
      { id: "18000", label: "18.000,00 $" },
      { id: "22000", label: "22.000,00 $" },
      { id: "26000", label: "26.000,00 $" },
      { id: "30000", label: "30.000,00 $" },
      { id: "40000", label: "40.000,00 $" },
      { id: "50000", label: "50.000,00 $" },
    ],
  },
  {
    id: "price_to",
    label: "getInTouch_form.nameInput",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.priceToInput.placeholder",
    showSuggestionsOnFocus: true,
    clearButton: true,
    type: "autosuggest",
    options: [      
      { id: "0", label: "0" },
      { id: "1000", label: "1.000,00 $" },
      { id: "2000", label: "2.000,00 $" },
      { id: "5000", label: "5.000,00 $" },
      { id: "8000", label: "8.000,00 $" },
      { id: "10000", label: "10.000,00 $" },
      { id: "12000", label: "12.000,00 $" },
      { id: "14000", label: "14.000,00 $" },
      { id: "16000", label: "16.000,00 $" },
      { id: "18000", label: "18.000,00 $" },
      { id: "22000", label: "22.000,00 $" },
      { id: "26000", label: "26.000,00 $" },
      { id: "30000", label: "30.000,00 $" },
      { id: "40000", label: "40.000,00 $" },
      { id: "50000", label: "50.000,00 $" },
    ],
  },
  {
    id: "km_from",
    label: "getInTouch_form.nameInput",
    type: "text",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.areaFromInput.placeholder",
  },
  {
    id: "km_to",
    label: "getInTouch_form.nameInput",
    type: "text",
    size: { xs: 0, lg: 3 },
    isLabelVisible: false,
    placeholder: "getInTouch_form.areaToInput.placeholder",
  },
];

export const MAIN_SEARCH = {
  type: "post",
  inputs,
  hasSubmit: true,
  buttonLabel: "getInTouch_form.buttonLabel",
};
